global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'silverithm'
    scrape_interval: 2s
    metrics_path: /metrics
    static_configs:
      - targets: ['silverithm-backend:9101']