version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - silverithm_network
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3003:3003
    volumes:
      - ./cfg/grafana/provisioning:/etc/grafana/provisioning
      - ./cfg/grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - ./cfg/grafana/grafana.env
    networks:
      - silverithm_network
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411" # Expose the Zipkin UI port
    networks:
      - silverithm_network
  db:
    container_name: silverithm_db
    image: mysql
    environment:
      MYSQL_DATABASE: silverithm
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - silverithm_network

  redis:
    container_name: silverithm_redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - silverithm_network

  app:
    container_name: silverithm-backend
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://silverithm_db:3306/silverithm?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    restart: always
    networks:
      - silverithm_network

volumes:
  db-data:

networks:
  silverithm_network: