spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/documents/h2/bin/silverithm
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect




  #
  #logging:
  #  level:
  #    root: debug

