apiVersion: 1

groups:
  - name: memory-usage-alerts
    orgId: 1
    folder: silverithm-alerts
    interval: 1m
    rules:
      - uid: high-memory-usage
        title: 높은 메모리 사용량
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: PBFA97CFB590B2093
            model:
              expr: 'process_resident_memory_bytes{job="silverithm"} > 100000000'
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: '서버 메모리 사용량이 100MB를 초과합니다. 현재 사용량: {{ $value }}바이트'
          summary: 서버 메모리 사용량 과도
        labels:
          severity: warning 