apiVersion: 1

groups:
  - name: mysql-slow-query-alerts
    orgId: 1
    folder: silverithm-alerts
    interval: 1m
    rules:
      - uid: mysql-slow-query-alert
        title: MySQL 슬로우쿼리 감지
        condition: A
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: loki
              uid: loki
            model:
              expr: 'count_over_time({job="mysql_slow_query"}[5m]) > 0'
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: 'MySQL 슬로우쿼리가 감지되었습니다. 최근 5분간 {{ $value }}개의 슬로우쿼리가 발생했습니다.'
          summary: MySQL 슬로우쿼리 감지
        labels:
          severity: warning 