-- notifications 테이블의 type 컬럼에 새로운 enum 값 추가
-- 기존: VACATION_APPROVED, VACATION_REJECTED, VACATION_SUBMITTED, VACATION_REMINDER, GENERAL
-- 추가: MEMBER_JOIN_REQUESTED, MEMBER_JOIN_APPROVED, MEMBER_JOIN_REJECTED, NOTICE

ALTER TABLE notifications
MODIFY COLUMN type ENUM(
    'VACATION_APPROVED',
    'VACATION_REJECTED',
    'VACATION_SUBMITTED',
    'VACATION_REMINDER',
    'MEMBER_JOIN_REQUESTED',
    'MEMBER_JOIN_APPROVED',
    'MEMBER_JOIN_REJECTED',
    'NOTICE',
    'GENERAL'
) NOT NULL DEFAULT 'GENERAL' COMMENT '알림 타입';